version: '3.7'
services:
  mongo:
    hostname: mongo
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ~/data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network # 网络名称