version: '3.7'
services:
  demo:
    build:
        context: ./
        dockerfile: Dockerfile
    image: fank243/demo:1.0.0
    hostname: demo
    container_name: demo
    volumes:
      - ./antstar-admin.jar:/app/app.jar
    ports:
      - "8900:8900"
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge