version: '3.7'
services:
  # https://github.com/apache/skywalking-docker/blob/master/compose/docker-compose.yml
  skywalking-oap:
    image: apache/skywalking-oap-server:8.9.1
    container_name: skywalking-oap
    restart: always
    ports:
      - "11800:11800"
      - "12800:12800"
    volumes:
      - ./config/application.yml:/skywalking/config/application.yml  # 配置文件
      - ./ext-libs:/skywalking/ext-libs:ro  # 存放MySQL驱动jar
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      #      SW_ES_USER: elastic
      #      SW_ES_PASSWORD: 123456
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms512m -Xmx1024m"

  #      SW_STORAGE: mysql
  #      SW_JDBC_URL: jdbc:mysql://127.0.0.1:3306/fank243-skyworking?rewriteBatchedStatements=true
  #      SW_DATA_SOURCE_USER: root
  #      SW_DATA_SOURCE_PASSWORD: root
  #      # 是否更新ui_template表
  #      SW_ENABLE_UPDATE_UI_TEMPLATE: true
  #      JAVA_OPTS: "-Xms512m -Xmx1024m"

  skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    hostname: skywalking-ui
    container_name: skywalking
    restart: always
    environment:
      - SW_OAP_ADDRESS=127.0.0.1:12800
    ports:
      - "8010:8080"
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge
