version: '3.7'
services:
  filebeat:
    hostname: filebeat
    container_name: filebeat
    # https://hub.docker.com/r/elastic/filebeat
    image: elastic/filebeat:7.15.0
    restart: always
    # Need to override user so we can access the log files, and docker.soc
    user: root         
    # disable strict permission checks
    command: ["--strict.perms=false"]
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ~/data/elk/filebeat:/usr/share/filebeat/data          # 数据目录
      - ~/logs/elk/filebeat:/usr/share/filebeat/logs          # 日志目录
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml           # 配置文件
      - ./modules.d:/usr/share/filebeat/filebmodules.d            # 模块配置
      - /var/run/docker.sock:/var/run/docker.sock:ro              # docker.sock文件所在路径
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # docker 容器目录
      - ~/logs/nginx:/data/logs/nginx:ro                      # 映射需要解析的日志文件目录
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge

