version: '3.7'
services:
  yapi:
    hostname: yapi
    image: jayfong/yapi:latest
    container_name: yapi
    restart: unless-stopped
    volumes:
        - ./config.json:/yapi/config.json
    ports:
        - "3000:3000"
    depends_on:
        - mongo
    networks:
        - docker-network

networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge