version: '3.7'
services:
  es:
    hostname: es
    container_name: es
    # https://hub.docker.com/r/elastic/elasticsearch
    image: elastic/elasticsearch:7.15.2
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m  # jvm参数
      - TZ=Asia/Shanghai                # 设置上海时区 +0800
      - discovery.type=single-node      # 运行单例模式
      - TAKE_FILE_OWNERSHIP=true        # 跳过data、conf目录拥有者权限认证，否则需要给data、conf目录授权
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml   # 配置文件
      - ~/data/elk/elasticsearch:/usr/share/elasticsearch/data                   # 数据目录
      - ~/logs/elk/elasticsearch:/usr/share/elasticsearch/logs                  # 日志目录
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge

