version: '3.7'
services: 
  gitea:
    image: gitea/gitea:1.15
    hostname: gitea
    container_name: gitea
    restart: always
    volumes:
      - ~/data/gitea:/data
    networks:
      - docker-network
    ports:
      - 3000:3000

networks:
  docker-network:
    name: docker-network
    driver: bridge
