version: '3.7'
services:
  sentinel:
    image: fank243/sentinel-dashboard:1.8.2
    hostname: sentinel
    container_name: sentinel
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./sentinel.properties:/app/application.properties
      - /home/logs/sentinel:/root/logs/csp
    ports:
      - "8858:8858"
      - "8719:8719"
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          cpus: '0.5'     # 限制CPU最高占用：50%
          memory: 200M    # 限制内存最高占用：200M
  
networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge
      