version: '3.7'
services:
  kibana:
    hostname: kibana
    container_name: kibana
    # https://hub.docker.com/r/elastic/filebeat
    image: elastic/kibana:7.15.0
    restart: always
    environment: 
      - TZ=Asia/Shanghai                # 设置上海时区 +0800
    volumes:
      - TAKE_FILE_OWNERSHIP=true
      - /home/data/elk/kibana:/usr/share/kibana/data    # 数据目录
      - ./conf:/usr/share/kibana/config    # 配置目录
    ports:
      - 5601:5601
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge

