version: '3.7'
services:
  nextcloud:
    image: nextcloud:23.0
    hostname: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - /home/data/nextcloud:/var/www/html
    ports:
      - "8080:80"
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge
