version: '3.7'
services:
  redis:
    hostname: redis
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/jason/devops/data/redis:/data/redis/data   # redis.conf中的dir路径也需保持一致
      - ./conf:/etc/redis
      - /home/jason/logs/redis:/data/redis/logs
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: '1024' # 可以解决TCP backlog(net.core.somaxconn)内核参数过低(默认:128)导致启动出现警告日志的问题
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          cpus: '0.2'     # 限制CPU最高占用：20%
          memory: 64M    # 限制内存最高占用：64M
networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge
      