version: '3'
services:
  nps:
    image: ffdfgdfg/nps:latest
    hostname: nps
    container_name: nps
    restart: unless-stopped
    volumes:
      - ./nps-conf:/nps/conf
    ports:
      - "8000-8002:8000-8002"
    networks:
      - docker-network
  
networks:
  docker-network:
    name: docker-network
    driver: bridge
        
  