version: '3'
services:
  nps:
    image: ffdfgdfg/nps:latest
    hostname: nps
    container_name: nps
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nps-conf:/conf
    ports:
      - "8000-8002:8000-8002"
  