version: '3.7'
services:
  nginx:
    hostname: nginx
    image: nginx:1.21
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf.d
      - ~/www/html:/home/www/html
    #  - /data/logs/nginx:/var/log/nginx # 如果需要开启gelf日志，则不能将日志从容器映射到本地
    ports:
      - "80:80"
      - "443:443"
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://127.0.0.1:12201"
#        tag: nginx 
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge
      
{"@timestamp":"$time_iso8601",
"@source":"$server_addr",
"hostname":"$hostname",
"ip":"$http_x_forwarded_for",
"client":"$remote_addr",
"request_method":"$request_method",
"scheme":"$scheme",
"domain":"$server_name",
"referer":"$http_referer",
"request":"$request_uri",
"args":"$args",
"size":$body_bytes_sent,
"status": $status,
"responsetime":$request_time,
"upstreamtime":"$upstream_response_time",
"upstreamaddr":"$upstream_addr",
"http_user_agent":"$http_user_agent",
"https":"$https"
};

