version: '3.7'
services:
  nginx:
    image: nginx:1.21-alpine
    hostname: nginx
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf.d
      - /home/data/nginx/html:/home/www/html
    #  - /data/logs/nginx:/var/log/nginx # 如果需要开启gelf日志，则不能将日志从容器映射到本地
    ports:
      - "80:80"
      - "443:443"
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://127.0.0.1:12201"
#        tag: nginx 
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge
      

