version: '3.7'
services:
  graylog:
    hostname: graylog
    image: graylog/graylog:4.1.0
    container_name: graylog
    restart: always
    volumes:
      # Mount local configuration directory into Docker container
      - ./conf/graylog.conf:/usr/share/graylog/data/config/graylog.conf
      - ~/data/graylog:/usr/share/graylog/data/journal
      # - ./geoLite/GeoLite2-City.mmdb:/etc/graylog/server/GeoLite2-City.mmdb # IP地址库
    networks:
      - docker-network
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      - 12201-12202:12201-12202/udp

networks:
  docker-network:
    name: docker-network
    driver: bridge
