version: '3.7'
services:
  # Graylog: https://hub.docker.com/r/graylog/graylog/      
  graylog:
    hostname: graylog
    image: graylog/graylog:3.2
    container_name: graylog
    restart: unless-stopped
    volumes:
      # Mount local configuration directory into Docker container
      - ./config:/usr/share/graylog/data/config
      - /data/data/graylog:/usr/share/graylog/data/journal
<<<<<<< HEAD
=======
      - ./geoLite/GeoLite2-City.mmdb:/etc/graylog/server/GeoLite2-City.mmdb # IP地址库
>>>>>>> e5ac84c2bb38cd3a8c7af9f11a74b591f48a0b00
    networks:
      - docker-network
    ports:
      # Graylog web interface and REST API
      - 9000:9000
<<<<<<< HEAD
      - 5044:5044
      - 12201:12201/udp
      - 12401:12401/udp
=======
      - 5044:5044/udp
      - 12200-12204:12200-12204
      - 12200-12204:12200-12204/udp
>>>>>>> e5ac84c2bb38cd3a8c7af9f11a74b591f48a0b00

networks:
  docker-network:
    name: docker-network
    driver: bridge
