version: '3.7'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password #设置utf8字符集
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/jason/devops/data/mysql:/var/lib/mysql   # 数据目录
 #     - ./conf:/etc/mysql                    # 配置文件目录
    ports:  
      - "3306:3306"
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge
      
