version: '3.7'
services:
  yapi:
    hostname: postgres
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=RNAe3uUtptxANRh8S
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge
