version: '3.7'
services:
  # https://raw.githubusercontent.com/bitnami/bitnami-docker-kafka/master/docker-compose.yml
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "E:/data/zookeeper:/bitnami/zookeeper/data"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.8.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "E:/data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    links: 
      - zookeeper
      
  eagle:
    image: fank243/kafka-eagle:2.0.9
    container_name: eagle
    ports:
      - "8048:8048"
    volumes:
      - ./conf/system-config.properties:/kafka-eagle/conf/system-config.properties
    links: 
      - zookeeper