version: '3.7'
services:
  logstash:
    hostname: logstash
    container_name: logstash
    image: logstash:7.6.1
    restart: always
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/data/elk/logstash:/usr/share/logstash/data    # 数据目录
      - ./conf:/usr/share/logstash/config   # 配置目录
    ports:
      - 5000:5000
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge

