version: '3.7'
services:
  npc:
    hostname: npc
    image: ffdfgdfg/npc:0.25.3
    container_name: npc
    restart: unless-stopped
    volumes:
      - ./conf:/conf
    logging:
      driver: gelf
      options:
          gelf-address: "udp://graylog:12401"
          tag: nginx  
    networks:
      - docker-network
  
networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge
  